networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  # Caddy certs and config
  caddy-data:
  caddy-config:

services:
  web:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - app-network
    volumes:
      - .:/app
      - caddy-data:/data
      - caddy-config:/config
    post_start:
      - command: ./docker/local/post_start.sh
        working_dir: /app
        user: www-data
    tty: true
    environment:
      - SERVER_NAME=:8882

  db:
    image: mysql:9.1
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
